ci: add check YC_NETWORK_ID

diff --git a/.github/workflows/CICD.yml b/.github/workflows/CICD.yml
--- a/.github/workflows/CICD.yml
+++ b/.github/workflows/CICD.yml
@@ -20,11 +20,14 @@ jobs:
         run: |
          echo "YC_FOLDER_ID: '${YC_FOLDER_ID}'"
          echo "DB_KEY: '${DB_KEY}'"
+         echo "YC_NETWORK_ID: '${YC_NETWORK_ID}'"
          if [ -z "$YC_FOLDER_ID" ]; then echo "ERROR: YC_FOLDER_ID is missing!" && exit 1; fi
          if [ -z "$DB_KEY" ]; then echo "ERROR: DB_KEY is missing!" && exit 1; fi
+          if [ -z "$YC_NETWORK_ID" ]; then echo "ERROR: YC_NETWORK_ID is missing!" && exit 1; fi
         env:
          YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
          DB_KEY: ${{ secrets.DB_KEY }}
+         YC_NETWORK_ID: ${{secrets.YC_NETWORK_ID}}
 
       # 3. Упаковываем всё для деплоя в одну папку
       - name: Prepare deployable package
